blank_issues_enabled: false
contact_links:
  - name: Test
    url: https://github.com/styles-wiki/styles-wiki
    about: For "real issues" such as bug reports, feature requests, roadmap questions etc
